"use client";

// frontend/app/(dashboard)/student/disciplinary-records/add/page.tsx
import React from "react";

// --- Mock Shadcn UI Component Mockups (Integrated for self-contained execution) ---
// These are simplified versions to make the code runnable in this environment.
// In a real Next.js project, you would have these components generated by shadcn/ui CLI
// and imported from '@/components/ui/...'
interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  type?: string;
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={`flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${className}`}
        ref={ref}
        {...props}
      />
    );
  }
);
Input.displayName = "Input";

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "default" | "outline" | "secondary" | "ghost" | "link";
  size?: "default" | "sm" | "lg" | "icon";
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "default", size = "default", ...props }, ref) => {
    const baseClasses =
      "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50";
    const variantClasses = {
      default: "bg-blue-600 text-white hover:bg-blue-700",
      outline:
        "border border-blue-400 bg-transparent text-blue-600 hover:bg-blue-50",
      secondary: "bg-gray-200 text-gray-800 hover:bg-gray-300",
      ghost: "hover:bg-gray-100 hover:text-gray-900",
      link: "text-blue-600 underline-offset-4 hover:underline",
    };
    const sizeClasses = {
      default: "h-10 px-4 py-2",
      sm: "h-9 rounded-md px-3",
      lg: "h-11 rounded-md px-8",
      icon: "h-10 w-10",
    };
    return (
      <button
        className={`${baseClasses} ${variantClasses[variant]} ${sizeClasses[size]} ${className}`}
        ref={ref}
        {...props}
      />
    );
  }
);
Button.displayName = "Button";

interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {}

const Label = React.forwardRef<HTMLLabelElement, LabelProps>(
  ({ className, ...props }, ref) => (
    <label
      ref={ref}
      className={`text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 ${className}`}
      {...props}
    />
  )
);
Label.displayName = "Label";

// DatePicker component definition (copied from student-disciplinary-records-form)
interface DatePickerProps {
  selectedDate: Date | null;
  onSelectDate: (date: Date | null) => void;
  placeholder?: string;
}

const DatePicker: React.FC<DatePickerProps> = ({
  selectedDate,
  onSelectDate,
  placeholder = "Select a date",
}) => {
  const [isOpen, setIsOpen] = React.useState(false);

  const toggleCalendar = () => setIsOpen(!isOpen);

  const handleDateClick = (day: number) => {
    const newDate = new Date();
    newDate.setDate(day);
    onSelectDate(newDate);
    setIsOpen(false);
  };

  const daysInMonth = Array.from({ length: 31 }, (_, i) => i + 1); // Simplified for demo

  return (
    <div className="relative">
      <Button
        variant="outline"
        className="w-full justify-start text-left font-normal"
        onClick={toggleCalendar}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="mr-2 h-4 w-4"
        >
          <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
          <line x1="16" x2="16" y1="2" y2="6" />
          <line x1="8" x2="8" y1="2" y2="6" />
          <line x1="3" x2="21" y1="10" y2="10" />
        </svg>
        {selectedDate ? (
          selectedDate.toDateString()
        ) : (
          <span>{placeholder}</span>
        )}
      </Button>
      {isOpen && (
        <div className="absolute z-50 mt-1 rounded-md border bg-popover p-3 text-popover-foreground shadow-md">
          <div className="grid grid-cols-7 gap-2">
            {daysInMonth.map((day) => (
              <Button
                key={day}
                variant="ghost"
                size="sm"
                className="h-8 w-8 p-0"
                onClick={() => handleDateClick(day)}
              >
                {day}
              </Button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
// --- End Shadcn UI Component Mockups ---

// Define interface for Disciplinary Records data
interface StudentDisciplinaryRecord {
  incidentDate: Date | null;
  incidentType: string;
  description: string;
  actionTaken: string;
  notes: string;
  studentId: string; // Added to link to a student
  studentName: string; // For display purposes
}

/**
 * AddDisciplinaryRecordForm component for adding new disciplinary records for a student.
 * This is a simplified version for a single record addition.
 */
export default function AddDisciplinaryRecordPage() {
  const [formData, setFormData] = React.useState<StudentDisciplinaryRecord>({
    incidentDate: null,
    incidentType: "",
    description: "",
    actionTaken: "",
    notes: "",
    studentId: "", // To be filled by user
    studentName: "", // To be filled by user
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { id, value } = e.target;
    setFormData((prev) => ({ ...prev, [id]: value }));
  };

  const handleDateChange = (date: Date | null) => {
    setFormData((prev) => ({ ...prev, incidentDate: date }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (
      formData.incidentDate &&
      formData.incidentType &&
      formData.description &&
      formData.studentId &&
      formData.studentName
    ) {
      // In a real application, you'd generate a unique ID and send this data to the backend.
      const newRecord = {
        ...formData,
        id: `DR${Math.random().toString(36).substring(2, 8).toUpperCase()}`, // Simple mock ID generation
      };
      console.log("New Disciplinary Record Data:", newRecord);
      alert("Disciplinary record added successfully! Check console for data.");
      // Optionally, clear the form or redirect to the disciplinary records list page
      setFormData({
        incidentDate: null,
        incidentType: "",
        description: "",
        actionTaken: "",
        notes: "",
        studentId: "",
        studentName: "",
      });
    } else {
      alert(
        "Please fill in all required fields (Student ID, Student Name, Date, Type, Description)."
      );
    }
  };

  return (
    <div className="container mx-auto p-4 sm:p-6 lg:p-8 bg-gray-50">
      <div className="w-full max-w-3xl mx-auto bg-white p-6 sm:p-8 rounded-xl shadow-lg border border-gray-200">
        <h1 className="text-3xl font-bold text-center text-gray-800 mb-8">
          Add New Disciplinary Record
        </h1>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Student Information */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="studentId">Student ID</Label>
              <Input
                id="studentId"
                type="text"
                placeholder="e.g., STU001"
                value={formData.studentId}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <Label htmlFor="studentName">Student Name</Label>
              <Input
                id="studentName"
                type="text"
                placeholder="e.g., Alice Johnson"
                value={formData.studentName}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          {/* Incident Details */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="incidentDate">Incident Date</Label>
              <DatePicker
                selectedDate={formData.incidentDate}
                onSelectDate={handleDateChange}
                placeholder="Select date"
              />
            </div>
            <div>
              <Label htmlFor="incidentType">Incident Type</Label>
              <Input
                id="incidentType"
                type="text"
                placeholder="e.g., Tardiness, Disruptive Behavior"
                value={formData.incidentType}
                onChange={handleChange}
                required
              />
            </div>
          </div>
          <div>
            <Label htmlFor="description">Description</Label>
            <textarea
              id="description"
              placeholder="Detailed description of the incident."
              value={formData.description}
              onChange={handleChange}
              rows={3}
              className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              required
            />
          </div>
          <div>
            <Label htmlFor="actionTaken">Action Taken</Label>
            <textarea
              id="actionTaken"
              placeholder="e.g., Warning, Detention, Parent Meeting"
              value={formData.actionTaken}
              onChange={handleChange}
              rows={2}
              className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
            />
          </div>
          <div>
            <Label htmlFor="notes">Additional Notes</Label>
            <textarea
              id="notes"
              placeholder="Any other relevant notes."
              value={formData.notes}
              onChange={handleChange}
              rows={2}
              className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
            />
          </div>

          <Button
            type="submit"
            className="w-full py-2 rounded-lg text-lg font-semibold shadow-md hover:shadow-lg transition-all duration-300 bg-blue-600 hover:bg-blue-700 text-white mt-6"
          >
            Add Disciplinary Record
          </Button>
        </form>
      </div>
    </div>
  );
}
